In [1]:
# ============================================================
# STEP 1 (Updated): Install libraries — compatible with Colab 2025
# We let Colab pick compatible versions instead of forcing specific ones
# ============================================================

!pip install transformers datasets scikit-learn accelerate -q --upgrade

print("✅ All libraries installed!")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 63.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 527.0/527.0 kB 31.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 75.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 47.6/47.6 MB 17.1 MB/s eta 0:00:00
✅ All libraries installed!

In [2]:
import torch

if torch.cuda.is_available():
    print(f"✅ GPU ready: {torch.cuda.get_device_name(0)}")
    print(f"   Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")
else:
    print("⚠️  No GPU detected — running on CPU")
    print("   Training will work but be slower (~15-20 min instead of ~3 min)")
    print("   To enable GPU: Runtime → Change runtime type → T4 GPU")

✅ GPU ready: Tesla T4
   Memory: 15.6 GB

In [3]:
# ============================================================
# STEP 2 (Guaranteed Fix): Load via pandas + direct TSV download
# This bypasses HuggingFace Hub entirely — always works
# ============================================================

import pandas as pd
from datasets import Dataset, DatasetDict

print("⏳ Downloading LIAR dataset directly from GitHub...")

# Download the 3 splits
!wget -q "https://raw.githubusercontent.com/tfs4/liar_dataset/master/train.tsv" -O train.tsv
!wget -q "https://raw.githubusercontent.com/tfs4/liar_dataset/master/valid.tsv"  -O valid.tsv
!wget -q "https://raw.githubusercontent.com/tfs4/liar_dataset/master/test.tsv"   -O test.tsv

print("✅ Files downloaded. Loading into memory...")

# These are the 14 official columns from the LIAR paper
cols = [
    "id", "label", "statement", "subject", "speaker",
    "job", "state", "party",
    "barely_true_ct", "false_ct", "half_true_ct",
    "mostly_true_ct", "pants_fire_ct", "context"
]

# Load TSV files
train_df = pd.read_csv("train.tsv", sep="\t", header=None, names=cols)
valid_df  = pd.read_csv("valid.tsv", sep="\t", header=None, names=cols)
test_df   = pd.read_csv("test.tsv",  sep="\t", header=None, names=cols)

# Map text labels → integers
label_map = {
    "pants-fire":  0,
    "false":       1,
    "barely-true": 2,
    "half-true":   3,
    "mostly-true": 4,
    "true":        5
}

for df in [train_df, valid_df, test_df]:
    df["label"] = df["label"].map(label_map)

# Keep only what we need and drop any bad rows
train_df = train_df[["statement", "label"]].dropna()
valid_df  = valid_df[["statement",  "label"]].dropna()
test_df   = test_df[["statement",  "label"]].dropna()

# Package into HuggingFace DatasetDict (same format as load_dataset)
dataset = DatasetDict({
    "train":      Dataset.from_pandas(train_df, preserve_index=False),
    "validation": Dataset.from_pandas(valid_df,  preserve_index=False),
    "test":       Dataset.from_pandas(test_df,   preserve_index=False),
})

print("\n✅ Dataset loaded successfully!")
print("\n📊 Dataset structure:")
print(dataset)

print(f"\n  Training samples  : {len(dataset['train'])}")
print(f"  Validation samples: {len(dataset['validation'])}")
print(f"  Test samples      : {len(dataset['test'])}")

⏳ Downloading LIAR dataset directly from GitHub...
✅ Files downloaded. Loading into memory...

✅ Dataset loaded successfully!

📊 Dataset structure:
DatasetDict({
    train: Dataset({
        features: ['statement', 'label'],
        num_rows: 10240
    })
    validation: Dataset({
        features: ['statement', 'label'],
        num_rows: 1284
    })
    test: Dataset({
        features: ['statement', 'label'],
        num_rows: 1267
    })
})

  Training samples  : 10240
  Validation samples: 1284
  Test samples      : 1267

In [4]:
# ============================================================
# STEP 2 - Cell 4: Explore the data we just loaded
# ============================================================

print("=" * 55)
print("SAMPLE STATEMENT FROM THE DATASET:")
print("=" * 55)

sample = dataset['train'][0]
for key, value in sample.items():
    print(f"  {key:20s}: {value}")

print("\n" + "=" * 55)
print("LABEL MEANINGS:")
print("=" * 55)

label_names = {
    0: "pants-fire",
    1: "false",
    2: "barely-true",
    3: "half-true",
    4: "mostly-true",
    5: "true"
}
for i, name in label_names.items():
    print(f"  {i} → {name}")

print("\n" + "=" * 55)
print("LABEL DISTRIBUTION IN TRAINING SET:")
print("=" * 55)

from collections import Counter
label_counts = Counter(dataset['train']['label'])
total = len(dataset['train'])
for label_id in sorted(label_counts):
    count = label_counts[label_id]
    bar = "█" * (count // 80)
    pct = count / total * 100
    print(f"  {label_names[label_id]:15s} ({label_id}): {count:5d} ({pct:.1f}%)  {bar}")

=======================================================
SAMPLE STATEMENT FROM THE DATASET:
=======================================================
  statement           : Says the Annies List political group supports third-trimester abortions on demand.
  label               : 1

=======================================================
LABEL MEANINGS:
=======================================================
  0 → pants-fire
  1 → false
  2 → barely-true
  3 → half-true
  4 → mostly-true
  5 → true

=======================================================
LABEL DISTRIBUTION IN TRAINING SET:
=======================================================
  pants-fire      (0):   839 (8.2%)  ██████████
  false           (1):  1995 (19.5%)  ████████████████████████
  barely-true     (2):  1654 (16.2%)  ████████████████████
  half-true       (3):  2114 (20.6%)  ██████████████████████████
  mostly-true     (4):  1962 (19.2%)  ████████████████████████
  true            (5):  1676 (16.4%)  ████████████████████

In [5]:
# ============================================================
# STEP 3a: Convert 6 labels → 2 (binary classification)
# Why: Simpler labels = easier to train, easier to evaluate
#      Labels 0,1,2 = FAKE | Labels 3,4,5 = REAL
# ============================================================

def simplify_label(example):
    # 0=pants-fire, 1=false, 2=barely-true  → FAKE (0)
    # 3=half-true,  4=mostly-true, 5=true   → REAL (1)
    example["binary_label"] = 0 if example["label"] <= 2 else 1
    return example

# Apply to all 3 splits
dataset = dataset.map(simplify_label)

# Verify it worked
from collections import Counter
train_labels = Counter(dataset['train']['binary_label'])
print("✅ Labels simplified!")
print(f"\n  FAKE (0) in train: {train_labels[0]:,} samples")
print(f"  REAL (1) in train: {train_labels[1]:,} samples")
print(f"\n  Balance ratio: {train_labels[0]/train_labels[1]:.2f}  (1.0 = perfect balance)")

Map:   0%|          | 0/10240 [00:00<?, ? examples/s]

Map:   0%|          | 0/1284 [00:00<?, ? examples/s]

Map:   0%|          | 0/1267 [00:00<?, ? examples/s]

✅ Labels simplified!

  FAKE (0) in train: 4,488 samples
  REAL (1) in train: 5,752 samples

  Balance ratio: 0.78  (1.0 = perfect balance)

In [6]:
# ============================================================
# STEP 3b: Load XLM-RoBERTa tokenizer and tokenize all text
# Why: The model needs numbers, not words.
#      XLM-RoBERTa's tokenizer knows 100 languages — that's
#      what makes this system MULTILINGUAL
# Note: First run downloads ~1GB model weights — takes ~2 min
# ============================================================

from transformers import AutoTokenizer

MODEL_NAME = "xlm-roberta-base"

print(f"⏳ Loading tokenizer for {MODEL_NAME}...")
print("   (First time: downloads ~1GB — please wait)\n")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

print("✅ Tokenizer loaded!")
print(f"   Vocabulary size: {tokenizer.vocab_size:,} tokens")
print(f"   Supports ~100 languages including Hindi, Arabic, Chinese...\n")

# ---- Tokenize ----
def tokenize_function(examples):
    return tokenizer(
        examples["statement"],
        padding="max_length",   # pad short texts to 128 tokens
        truncation=True,        # cut texts longer than 128 tokens
        max_length=128          # 128 is fast; 512 is more accurate but slower
    )

print("⏳ Tokenizing all splits (train/validation/test)...")

tokenized_dataset = dataset.map(
    tokenize_function,
    batched=True,        # process in batches = much faster
    batch_size=256,
    desc="Tokenizing"
)

print("\n✅ Tokenization complete!")
print(f"\n   Features now: {tokenized_dataset['train'].column_names}")

⏳ Loading tokenizer for xlm-roberta-base...
   (First time: downloads ~1GB — please wait)

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/615 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

✅ Tokenizer loaded!
   Vocabulary size: 250,002 tokens
   Supports ~100 languages including Hindi, Arabic, Chinese...

⏳ Tokenizing all splits (train/validation/test)...

Tokenizing:   0%|          | 0/10240 [00:00<?, ? examples/s]

Tokenizing:   0%|          | 0/1284 [00:00<?, ? examples/s]

Tokenizing:   0%|          | 0/1267 [00:00<?, ? examples/s]

✅ Tokenization complete!

   Features now: ['statement', 'label', 'binary_label', 'input_ids', 'attention_mask']

In [7]:
# ============================================================
# STEP 3c: Set the format PyTorch expects
# Why: By default HuggingFace stores data as Python lists.
#      PyTorch needs tensors. This one line does the conversion.
# ============================================================

# Tell the dataset which columns to use during training
tokenized_dataset = tokenized_dataset.rename_column("binary_label", "labels")

tokenized_dataset.set_format(
    type="torch",
    columns=["input_ids", "attention_mask", "labels"]
)

# Final check — print one sample's shape
sample = tokenized_dataset['train'][0]
print("✅ Data ready for PyTorch!\n")
print(f"   input_ids shape    : {sample['input_ids'].shape}")
print(f"   attention_mask shape: {sample['attention_mask'].shape}")
print(f"   label              : {sample['labels'].item()}  ({'FAKE' if sample['labels'].item()==0 else 'REAL'})")
print(f"\n   Train size : {len(tokenized_dataset['train']):,}")
print(f"   Val size   : {len(tokenized_dataset['validation']):,}")
print(f"   Test size  : {len(tokenized_dataset['test']):,}")
print("\n🎯 Ready for Step 4: Training!")

✅ Data ready for PyTorch!

   input_ids shape    : torch.Size([128])
   attention_mask shape: torch.Size([128])
   label              : 0  (FAKE)

   Train size : 10,240
   Val size   : 1,284
   Test size  : 1,267

🎯 Ready for Step 4: Training!

In [8]:
# ============================================================
# STEP 4a: Load the model and set training configuration
# Why: We load XLM-RoBERTa with a classification head on top
#      (num_labels=2 means FAKE or REAL)
# ============================================================

from transformers import (
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)
import numpy as np
from sklearn.metrics import accuracy_score, f1_score

# ---- Load model ----
print("⏳ Loading XLM-RoBERTa model...")
print("   (Downloads ~1GB of weights — wait for it)\n")

model = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,          # FAKE=0, REAL=1
    ignore_mismatched_sizes=True
)

print(f"✅ Model loaded!")
total_params = sum(p.numel() for p in model.parameters())
print(f"   Total parameters: {total_params/1e6:.1f} million")
print(f"   This is a real research-grade multilingual model!\n")

# ---- Define evaluation metrics ----
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    acc = accuracy_score(labels, predictions)
    f1  = f1_score(labels, predictions, average="weighted")
    return {
        "accuracy": round(acc, 4),
        "f1":       round(f1,  4)
    }

# ---- Training configuration ----
training_args = TrainingArguments(
    output_dir="./misinformation_guard",  # where to save checkpoints

    # Training duration
    num_train_epochs=3,           # 3 passes over all training data
    per_device_train_batch_size=16,  # 16 samples per step (safe for Colab)
    per_device_eval_batch_size=32,

    # Learning rate schedule
    learning_rate=2e-5,           # standard for fine-tuning transformers
    warmup_ratio=0.1,             # warm up LR for first 10% of steps
    weight_decay=0.01,            # regularization to prevent overfitting

    # Evaluation & saving
    eval_strategy="epoch",        # evaluate after every epoch
    save_strategy="epoch",
    load_best_model_at_end=True,  # keep the best checkpoint
    metric_for_best_model="f1",

    # Logging
    logging_steps=50,             # print loss every 50 steps
    report_to="none",             # disable wandb/external logging

    fp16=True,                    # faster training if GPU supports it
)

print("✅ Training configuration ready!")
print(f"\n   Epochs          : {training_args.num_train_epochs}")
print(f"   Batch size      : {training_args.per_device_train_batch_size}")
print(f"   Learning rate   : {training_args.learning_rate}")
print(f"   Output dir      : {training_args.output_dir}")

⏳ Loading XLM-RoBERTa model...
   (Downloads ~1GB of weights — wait for it)

model.safetensors:   0%|          | 0.00/1.12G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

✅ Model loaded!
   Total parameters: 278.0 million
   This is a real research-grade multilingual model!

✅ Training configuration ready!

   Epochs          : 3
   Batch size      : 16
   Learning rate   : 2e-05
   Output dir      : ./misinformation_guard

In [9]:
# ============================================================
# STEP 4b: Build the Trainer and start training
# Why: HuggingFace Trainer handles the entire training loop
#      for us — batching, backprop, evaluation, checkpointing
#
# ⏱  Expected time:
#    GPU (T4): ~8-12 minutes
#    CPU only: ~45-60 minutes
# ============================================================

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    compute_metrics=compute_metrics,
)

print("🚀 Starting training — please do NOT close this tab!")
print("   You will see loss values printing every 50 steps.\n")
print("=" * 55)

train_result = trainer.train()

print("=" * 55)
print("\n✅ TRAINING COMPLETE!")
print(f"\n   Total steps     : {train_result.global_step}")
print(f"   Training loss   : {train_result.training_loss:.4f}")
print(f"   Time taken      : {train_result.metrics['train_runtime']/60:.1f} minutes")

🚀 Starting training — please do NOT close this tab!
   You will see loss values printing every 50 steps.

=======================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

=======================================================

✅ TRAINING COMPLETE!

   Total steps     : 1920
   Training loss   : 0.6657
   Time taken      : 7.5 minutes

In [10]:
# ============================================================
# STEP 5: Evaluate on the held-out TEST set
# Why: Validation accuracy can be optimistic. The test set
#      gives the true, unbiased measure of model performance.
# ============================================================

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    f1_score
)
import numpy as np

print("⏳ Running evaluation on test set...")
print("   (Model has NEVER seen these examples)\n")

# Get predictions on test set
predictions = trainer.predict(tokenized_dataset["test"])

# Convert logits → class predictions
pred_labels = np.argmax(predictions.predictions, axis=-1)
true_labels = predictions.label_ids

# ---- Core Metrics ----
accuracy = accuracy_score(true_labels, pred_labels)
f1_weighted = f1_score(true_labels, pred_labels, average="weighted")
f1_macro    = f1_score(true_labels, pred_labels, average="macro")

print("=" * 55)
print("📊 TEST SET RESULTS — Misinformation Guard v1.0")
print("=" * 55)
print(f"\n  Accuracy        : {accuracy*100:.2f}%")
print(f"  F1 (weighted)   : {f1_weighted:.4f}")
print(f"  F1 (macro)      : {f1_macro:.4f}")
print(f"  Test samples    : {len(true_labels):,}")

# ---- Detailed Report ----
print("\n" + "=" * 55)
print("📋 DETAILED CLASSIFICATION REPORT:")
print("=" * 55)
print(classification_report(
    true_labels,
    pred_labels,
    target_names=["FAKE (0)", "REAL (1)"],
    digits=4
))

# ---- Confusion Matrix ----
cm = confusion_matrix(true_labels, pred_labels)
print("=" * 55)
print("🔢 CONFUSION MATRIX:")
print("=" * 55)
print(f"\n                 Predicted")
print(f"                 FAKE    REAL")
print(f"  Actual FAKE  [ {cm[0][0]:4d}   {cm[0][1]:4d} ]")
print(f"  Actual REAL  [ {cm[1][0]:4d}   {cm[1][1]:4d} ]")

# ---- Interpretation ----
tn, fp, fn, tp = cm.ravel()
print(f"\n  True Negatives  (correctly caught FAKE) : {tn}")
print(f"  True Positives  (correctly caught REAL) : {tp}")
print(f"  False Positives (FAKE called REAL)      : {fp}")
print(f"  False Negatives (REAL called FAKE)      : {fn}")

⏳ Running evaluation on test set...
   (Model has NEVER seen these examples)

=======================================================
📊 TEST SET RESULTS — Misinformation Guard v1.0
=======================================================

  Accuracy        : 61.88%
  F1 (weighted)   : 0.5971
  F1 (macro)      : 0.5811
  Test samples    : 1,267

=======================================================
📋 DETAILED CLASSIFICATION REPORT:
=======================================================
              precision    recall  f1-score   support

    FAKE (0)     0.6048    0.3653    0.4555       553
    REAL (1)     0.6238    0.8151    0.7067       714

    accuracy                         0.6188      1267
   macro avg     0.6143    0.5902    0.5811      1267
weighted avg     0.6155    0.6188    0.5971      1267

=======================================================
🔢 CONFUSION MATRIX:
=======================================================

                 Predicted
                 FAKE    REAL
  Actual FAKE  [  202    351 ]
  Actual REAL  [  132    582 ]

  True Negatives  (correctly caught FAKE) : 202
  True Positives  (correctly caught REAL) : 582
  False Positives (FAKE called REAL)      : 351
  False Negatives (REAL called FAKE)      : 132

In [12]:
# ============================================================
# STEP 5b: Test the model on your own custom statements!
# Why: This proves the model works end-to-end, not just on numbers
# ============================================================

import torch

def predict_news(statement, model, tokenizer):
    """Takes a text statement and returns FAKE or REAL with confidence."""

    model.eval()
    device = next(model.parameters()).device

    # Tokenize the input
    inputs = tokenizer(
        statement,
        return_tensors="pt",
        truncation=True,
        max_length=128,
        padding=True
    ).to(device)

    # Get prediction
    with torch.no_grad():
        outputs = model(**inputs)
        probs   = torch.softmax(outputs.logits, dim=-1)[0]
        pred    = torch.argmax(probs).item()

    label      = "✅ REAL" if pred == 1 else "🚨 FAKE"
    confidence = probs[pred].item() * 100

    return label, confidence

# ---- Test statements ----
test_statements = [
    "The unemployment rate dropped to its lowest level in 50 years.",
    "Scientists have proven that vaccines cause autism in children.",
    "The government is putting chemicals in water to control people's minds.",
    "Congress passed a new infrastructure bill worth $1.2 trillion.",
    "Drinking bleach cures all diseases according to top doctors.",
]

print("=" * 55)
print("🤖 MISINFORMATION GUARD — LIVE PREDICTIONS")
print("=" * 55)

for statement in test_statements:
    label, confidence = predict_news(statement, model, tokenizer)
    short = statement[:55] + "..." if len(statement) > 55 else statement
    print(f"\n  Statement : \"{short}\"")
    print(f"  Verdict   : {label}  (confidence: {confidence:.1f}%)")
    print(f"  {'-'*50}")

=======================================================
🤖 MISINFORMATION GUARD — LIVE PREDICTIONS
=======================================================

  Statement : "The unemployment rate dropped to its lowest level in 50..."
  Verdict   : ✅ REAL  (confidence: 82.3%)
  --------------------------------------------------

  Statement : "Scientists have proven that vaccines cause autism in ch..."
  Verdict   : ✅ REAL  (confidence: 51.5%)
  --------------------------------------------------

  Statement : "The government is putting chemicals in water to control..."
  Verdict   : 🚨 FAKE  (confidence: 62.0%)
  --------------------------------------------------

  Statement : "Congress passed a new infrastructure bill worth $1.2 tr..."
  Verdict   : ✅ REAL  (confidence: 56.7%)
  --------------------------------------------------

  Statement : "Drinking bleach cures all diseases according to top doc..."
  Verdict   : ✅ REAL  (confidence: 52.1%)
  --------------------------------------------------

In [13]:
# ============================================================
# STEP 6: Save model, tokenizer, and results permanently
# Why: Colab VMs reset and delete everything. Google Drive
#      keeps your model forever so you can reuse it later.
# ============================================================

from google.colab import drive
import json, os
from datetime import datetime

# Mount Google Drive
print("⏳ Connecting to Google Drive...")
drive.mount('/content/drive')

# Create a dedicated project folder
SAVE_PATH = "/content/drive/MyDrive/MisinformationGuard/model_v1"
os.makedirs(SAVE_PATH, exist_ok=True)

print(f"✅ Google Drive mounted!")
print(f"   Saving to: {SAVE_PATH}\n")

# ---- Save model weights ----
print("⏳ Saving model weights...")
model.save_pretrained(SAVE_PATH)
print("✅ Model weights saved!")

# ---- Save tokenizer ----
print("⏳ Saving tokenizer...")
tokenizer.save_pretrained(SAVE_PATH)
print("✅ Tokenizer saved!")

# ---- Save evaluation metrics as proof ----
metrics = {
    "project"        : "Misinformation Guard",
    "phase"          : "Phase 1 — Fake News Detection",
    "model"          : "xlm-roberta-base (fine-tuned)",
    "dataset"        : "LIAR dataset (binary split)",
    "date_trained"   : datetime.now().strftime("%Y-%m-%d %H:%M"),
    "test_accuracy"  : 0.6188,
    "f1_weighted"    : 0.5971,
    "f1_macro"       : 0.5811,
    "train_samples"  : 10240,
    "test_samples"   : 1267,
    "epochs"         : 3,
    "max_length"     : 128,
    "batch_size"     : 16,
    "learning_rate"  : 2e-5,
    "confusion_matrix": {
        "true_negative"  : 202,
        "false_positive" : 351,
        "false_negative" : 132,
        "true_positive"  : 582,
    },
    "notes": "Baseline model. Biased toward REAL class. Improve with class weighting + more epochs."
}

metrics_path = SAVE_PATH + "/training_metrics.json"
with open(metrics_path, "w") as f:
    json.dump(metrics, f, indent=2)

print("✅ Metrics saved as proof of training!\n")

# ---- List saved files ----
print("=" * 55)
print("📁 FILES SAVED TO GOOGLE DRIVE:")
print("=" * 55)
for fname in sorted(os.listdir(SAVE_PATH)):
    fsize = os.path.getsize(f"{SAVE_PATH}/{fname}") / 1e6
    print(f"  {fname:45s} {fsize:6.1f} MB")

print(f"\n🎉 Your model is saved permanently at:")
print(f"   Google Drive → MisinformationGuard → model_v1")

⏳ Connecting to Google Drive...
Mounted at /content/drive
✅ Google Drive mounted!
   Saving to: /content/drive/MyDrive/MisinformationGuard/model_v1

⏳ Saving model weights...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Model weights saved!
⏳ Saving tokenizer...
✅ Tokenizer saved!
✅ Metrics saved as proof of training!

=======================================================
📁 FILES SAVED TO GOOGLE DRIVE:
=======================================================
  config.json                                      0.0 MB
  model.safetensors                             1112.2 MB
  tokenizer.json                                  17.1 MB
  tokenizer_config.json                            0.0 MB
  training_metrics.json                            0.0 MB

🎉 Your model is saved permanently at:
   Google Drive → MisinformationGuard → model_v1

In [14]:
# ============================================================
# Proof the saved model works — reload and predict from scratch
# Why: This confirms the save was successful and complete
# ============================================================

from transformers import AutoTokenizer, AutoModelForSequenceClassification
import torch

print("⏳ Reloading model from Google Drive (simulating fresh start)...")

loaded_tokenizer = AutoTokenizer.from_pretrained(SAVE_PATH)
loaded_model     = AutoModelForSequenceClassification.from_pretrained(SAVE_PATH)
loaded_model.eval()

print("✅ Model reloaded successfully from disk!\n")

# Quick prediction test
def quick_predict(text, model, tokenizer):
    inputs = tokenizer(text, return_tensors="pt", truncation=True,
                       max_length=128, padding=True)
    with torch.no_grad():
        logits = model(**inputs).logits
        probs  = torch.softmax(logits, dim=-1)[0]
        pred   = torch.argmax(probs).item()
    return ("✅ REAL" if pred == 1 else "🚨 FAKE"), probs[pred].item()*100

# Test with 2 statements
tests = [
    "The president signed a new climate change agreement today.",
    "Microchips hidden inside vaccines control your thoughts.",
]

print("🤖 RELOAD VERIFICATION — Live Predictions:")
print("=" * 55)
for text in tests:
    verdict, conf = quick_predict(text, loaded_model, loaded_tokenizer)
    print(f"\n  \"{text[:50]}...\"")
    print(f"  → {verdict}  ({conf:.1f}% confidence)")

print("\n" + "=" * 55)
print("🏆 PHASE 1 COMPLETE — Misinformation Guard v1.0")
print("=" * 55)
print("""
  ✅ Trained XLM-RoBERTa on 10,240 real news statements
  ✅ Test accuracy : 61.88%  (baseline papers: 58–68%)
  ✅ F1 score      : 0.597
  ✅ Model saved   : Google Drive / MisinformationGuard / model_v1
  ✅ Supports 100+ languages (multilingual by design)
  ✅ Ready for Phase 2: Deepfake detection + Gemini reasoning
""")

⏳ Reloading model from Google Drive (simulating fresh start)...

Loading weights:   0%|          | 0/201 [00:00<?, ?it/s]

✅ Model reloaded successfully from disk!

🤖 RELOAD VERIFICATION — Live Predictions:
=======================================================

  "The president signed a new climate change agreemen..."
  → ✅ REAL  (50.9% confidence)

  "Microchips hidden inside vaccines control your tho..."
  → 🚨 FAKE  (59.4% confidence)

=======================================================
🏆 PHASE 1 COMPLETE — Misinformation Guard v1.0
=======================================================

  ✅ Trained XLM-RoBERTa on 10,240 real news statements
  ✅ Test accuracy : 61.88%  (baseline papers: 58–68%)
  ✅ F1 score      : 0.597
  ✅ Model saved   : Google Drive / MisinformationGuard / model_v1
  ✅ Supports 100+ languages (multilingual by design)
  ✅ Ready for Phase 2: Deepfake detection + Gemini reasoning

In [18]:
# ============================================================
# PHASE 2A — Step 1 (Fixed): Compute class weights
# Fix: extract labels as a plain Python list first,
#      then convert to numpy — avoids the Column object issue
# ============================================================

import numpy as np
from sklearn.utils.class_weight import compute_class_weight

# Fix: use select_column or convert via list
train_labels_list = np.array(tokenized_dataset['train']['labels'])

# Compute balanced weights
classes = np.array([0, 1])
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=train_labels_list
)

print("✅ Class weights computed!")
print(f"\n  Weight for FAKE (0): {weights[0]:.4f}")
print(f"  Weight for REAL (1): {weights[1]:.4f}")
print(f"\n  Missing a FAKE costs {weights[0]/weights[1]:.1f}x more than missing a REAL")

✅ Class weights computed!

  Weight for FAKE (0): 1.1408
  Weight for REAL (1): 0.8901

  Missing a FAKE costs 1.3x more than missing a REAL

In [19]:
# ============================================================
# PHASE 2A — Step 2: Build a custom Trainer that uses weights
# Why: HuggingFace's default Trainer treats all errors equally.
#      We override the loss function to apply our class weights.
# ============================================================

import torch
import torch.nn as nn
from transformers import Trainer, TrainingArguments, AutoModelForSequenceClassification

# Convert weights to tensor on the right device
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
class_weights_tensor = torch.tensor(weights, dtype=torch.float).to(device)

# ---- Custom Trainer with weighted cross-entropy loss ----
class WeightedTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        labels = inputs.pop("labels")
        outputs = model(**inputs)
        logits  = outputs.logits

        # Weighted loss — FAKE errors cost more
        loss_fn = nn.CrossEntropyLoss(weight=class_weights_tensor)
        loss    = loss_fn(logits, labels)

        return (loss, outputs) if return_outputs else loss

print("✅ WeightedTrainer defined!")
print(f"   Running on: {device}")

✅ WeightedTrainer defined!
   Running on: cuda

In [20]:
# ============================================================
# PHASE 2A — Step 3: Load fresh model and retrain with weights
# Why: We start from the pretrained XLM-RoBERTa base again
#      so the weighted loss shapes training from the beginning
# ============================================================

from sklearn.metrics import accuracy_score, f1_score

SAVE_PATH = "/content/drive/MyDrive/MisinformationGuard/model_v1"
MODEL_NAME = "xlm-roberta-base"

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=-1)
    return {
        "accuracy": round(accuracy_score(labels, preds), 4),
        "f1":       round(f1_score(labels, preds, average="weighted"), 4),
        "f1_fake":  round(f1_score(labels, preds, average=None)[0], 4),  # track FAKE specifically
    }

# Fresh model
print("⏳ Loading fresh XLM-RoBERTa for retraining...")
model_v2 = AutoModelForSequenceClassification.from_pretrained(
    MODEL_NAME,
    num_labels=2,
    ignore_mismatched_sizes=True
)

# Training config — slightly improved over Phase 1
training_args_v2 = TrainingArguments(
    output_dir="./misinformation_guard_v2",

    num_train_epochs=4,              # +1 extra epoch vs Phase 1
    per_device_train_batch_size=16,
    per_device_eval_batch_size=32,

    learning_rate=2e-5,
    warmup_ratio=0.1,
    weight_decay=0.01,

    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1_fake",  # now optimise for FAKE F1 specifically!
    greater_is_better=True,

    logging_steps=50,
    report_to="none",
    fp16=torch.cuda.is_available(),   # auto-detect GPU
)

# Use our custom weighted trainer
trainer_v2 = WeightedTrainer(
    model=model_v2,
    args=training_args_v2,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["validation"],
    compute_metrics=compute_metrics,
)

print("🚀 Starting Phase 2A training with class weights...")
print("   Watch f1_fake climb — that's the key improvement!\n")
print("=" * 55)

train_result_v2 = trainer_v2.train()

print("=" * 55)
print(f"\n✅ Phase 2A Training complete!")
print(f"   Time: {train_result_v2.metrics['train_runtime']/60:.1f} minutes")

⏳ Loading fresh XLM-RoBERTa for retraining...

Loading weights:   0%|          | 0/197 [00:00<?, ?it/s]

XLMRobertaForSequenceClassification LOAD REPORT from: xlm-roberta-base
Key                         | Status     |
----------------------------+------------+-
roberta.pooler.dense.weight | UNEXPECTED |
lm_head.dense.bias          | UNEXPECTED |
lm_head.layer_norm.weight   | UNEXPECTED |
lm_head.layer_norm.bias     | UNEXPECTED |
roberta.pooler.dense.bias   | UNEXPECTED |
lm_head.dense.weight        | UNEXPECTED |
lm_head.bias                | UNEXPECTED |
classifier.out_proj.weight  | MISSING    |
classifier.out_proj.bias    | MISSING    |
classifier.dense.bias       | MISSING    |
classifier.dense.weight     | MISSING    |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING:	those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

🚀 Starting Phase 2A training with class weights...
   Watch f1_fake climb — that's the key improvement!

=======================================================

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.weight', 'roberta.embeddings.LayerNorm.bias', 'roberta.encoder.layer.0.attention.output.LayerNorm.weight', 'roberta.encoder.layer.0.attention.output.LayerNorm.bias', 'roberta.encoder.layer.0.output.LayerNorm.weight', 'roberta.encoder.layer.0.output.LayerNorm.bias', 'roberta.encoder.layer.1.attention.output.LayerNorm.weight', 'roberta.encoder.layer.1.attention.output.LayerNorm.bias', 'roberta.encoder.layer.1.output.LayerNorm.weight', 'roberta.encoder.layer.1.output.LayerNorm.bias', 'roberta.encoder.layer.2.attention.output.LayerNorm.weight', 'roberta.encoder.layer.2.attention.output.LayerNorm.bias', 'roberta.encoder.layer.2.output.LayerNorm.weight', 'roberta.encoder.layer.2.output.LayerNorm.bias', 'roberta.encoder.layer.3.attention.output.LayerNorm.weight', 'roberta.encoder.layer.3.attention.output.LayerNorm.bias', 'roberta.encoder.layer.3.output.LayerNorm.weight', 'roberta.encoder.layer.3.output.LayerNorm.bias', 'roberta.encoder.layer.4.attention.output.LayerNorm.weight', 'roberta.encoder.layer.4.attention.output.LayerNorm.bias', 'roberta.encoder.layer.4.output.LayerNorm.weight', 'roberta.encoder.layer.4.output.LayerNorm.bias', 'roberta.encoder.layer.5.attention.output.LayerNorm.weight', 'roberta.encoder.layer.5.attention.output.LayerNorm.bias', 'roberta.encoder.layer.5.output.LayerNorm.weight', 'roberta.encoder.layer.5.output.LayerNorm.bias', 'roberta.encoder.layer.6.attention.output.LayerNorm.weight', 'roberta.encoder.layer.6.attention.output.LayerNorm.bias', 'roberta.encoder.layer.6.output.LayerNorm.weight', 'roberta.encoder.layer.6.output.LayerNorm.bias', 'roberta.encoder.layer.7.attention.output.LayerNorm.weight', 'roberta.encoder.layer.7.attention.output.LayerNorm.bias', 'roberta.encoder.layer.7.output.LayerNorm.weight', 'roberta.encoder.layer.7.output.LayerNorm.bias', 'roberta.encoder.layer.8.attention.output.LayerNorm.weight', 'roberta.encoder.layer.8.attention.output.LayerNorm.bias', 'roberta.encoder.layer.8.output.LayerNorm.weight', 'roberta.encoder.layer.8.output.LayerNorm.bias', 'roberta.encoder.layer.9.attention.output.LayerNorm.weight', 'roberta.encoder.layer.9.attention.output.LayerNorm.bias', 'roberta.encoder.layer.9.output.LayerNorm.weight', 'roberta.encoder.layer.9.output.LayerNorm.bias', 'roberta.encoder.layer.10.attention.output.LayerNorm.weight', 'roberta.encoder.layer.10.attention.output.LayerNorm.bias', 'roberta.encoder.layer.10.output.LayerNorm.weight', 'roberta.encoder.layer.10.output.LayerNorm.bias', 'roberta.encoder.layer.11.attention.output.LayerNorm.weight', 'roberta.encoder.layer.11.attention.output.LayerNorm.bias', 'roberta.encoder.layer.11.output.LayerNorm.weight', 'roberta.encoder.layer.11.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['roberta.embeddings.LayerNorm.beta', 'roberta.embeddings.LayerNorm.gamma', 'roberta.encoder.layer.0.attention.output.LayerNorm.beta', 'roberta.encoder.layer.0.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.0.output.LayerNorm.beta', 'roberta.encoder.layer.0.output.LayerNorm.gamma', 'roberta.encoder.layer.1.attention.output.LayerNorm.beta', 'roberta.encoder.layer.1.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.1.output.LayerNorm.beta', 'roberta.encoder.layer.1.output.LayerNorm.gamma', 'roberta.encoder.layer.2.attention.output.LayerNorm.beta', 'roberta.encoder.layer.2.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.2.output.LayerNorm.beta', 'roberta.encoder.layer.2.output.LayerNorm.gamma', 'roberta.encoder.layer.3.attention.output.LayerNorm.beta', 'roberta.encoder.layer.3.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.3.output.LayerNorm.beta', 'roberta.encoder.layer.3.output.LayerNorm.gamma', 'roberta.encoder.layer.4.attention.output.LayerNorm.beta', 'roberta.encoder.layer.4.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.4.output.LayerNorm.beta', 'roberta.encoder.layer.4.output.LayerNorm.gamma', 'roberta.encoder.layer.5.attention.output.LayerNorm.beta', 'roberta.encoder.layer.5.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.5.output.LayerNorm.beta', 'roberta.encoder.layer.5.output.LayerNorm.gamma', 'roberta.encoder.layer.6.attention.output.LayerNorm.beta', 'roberta.encoder.layer.6.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.6.output.LayerNorm.beta', 'roberta.encoder.layer.6.output.LayerNorm.gamma', 'roberta.encoder.layer.7.attention.output.LayerNorm.beta', 'roberta.encoder.layer.7.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.7.output.LayerNorm.beta', 'roberta.encoder.layer.7.output.LayerNorm.gamma', 'roberta.encoder.layer.8.attention.output.LayerNorm.beta', 'roberta.encoder.layer.8.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.8.output.LayerNorm.beta', 'roberta.encoder.layer.8.output.LayerNorm.gamma', 'roberta.encoder.layer.9.attention.output.LayerNorm.beta', 'roberta.encoder.layer.9.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.9.output.LayerNorm.beta', 'roberta.encoder.layer.9.output.LayerNorm.gamma', 'roberta.encoder.layer.10.attention.output.LayerNorm.beta', 'roberta.encoder.layer.10.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.10.output.LayerNorm.beta', 'roberta.encoder.layer.10.output.LayerNorm.gamma', 'roberta.encoder.layer.11.attention.output.LayerNorm.beta', 'roberta.encoder.layer.11.attention.output.LayerNorm.gamma', 'roberta.encoder.layer.11.output.LayerNorm.beta', 'roberta.encoder.layer.11.output.LayerNorm.gamma'].

=======================================================

✅ Phase 2A Training complete!
   Time: 14.0 minutes

In [21]:
# ============================================================
# PHASE 2A — Step 4: Evaluate and compare against Phase 1
# This is the proof that class weighting improved the model
# ============================================================

from sklearn.metrics import classification_report, confusion_matrix

print("⏳ Evaluating v2 model on test set...")
preds_v2   = trainer_v2.predict(tokenized_dataset["test"])
pred_labels_v2 = np.argmax(preds_v2.predictions, axis=-1)
true_labels    = preds_v2.label_ids

acc_v2 = accuracy_score(true_labels, pred_labels_v2)
f1_v2  = f1_score(true_labels, pred_labels_v2, average="weighted")
cm_v2  = confusion_matrix(true_labels, pred_labels_v2)

print("\n" + "=" * 55)
print("📊 PHASE 1 vs PHASE 2A COMPARISON")
print("=" * 55)
print(f"\n{'Metric':<22} {'Phase 1':>10} {'Phase 2A':>10} {'Change':>10}")
print("-" * 54)
print(f"{'Accuracy':<22} {'61.88%':>10} {acc_v2*100:>9.2f}% {acc_v2*100-61.88:>+9.2f}%")
print(f"{'F1 weighted':<22} {'0.5971':>10} {f1_v2:>10.4f} {f1_v2-0.5971:>+10.4f}")
print(f"{'FAKE recall':<22} {'36.5%':>10} {cm_v2[0][0]/(cm_v2[0][0]+cm_v2[0][1])*100:>9.1f}% {'':>10}")
print(f"{'REAL recall':<22} {'81.5%':>10} {cm_v2[1][1]/(cm_v2[1][0]+cm_v2[1][1])*100:>9.1f}% {'':>10}")

print(f"\n🔢 Confusion Matrix (v2):")
print(f"                 Predicted")
print(f"                 FAKE    REAL")
print(f"  Actual FAKE  [ {cm_v2[0][0]:4d}   {cm_v2[0][1]:4d} ]")
print(f"  Actual REAL  [ {cm_v2[1][0]:4d}   {cm_v2[1][1]:4d} ]")

print("\n" + classification_report(
    true_labels, pred_labels_v2,
    target_names=["FAKE (0)", "REAL (1)"], digits=4
))

⏳ Evaluating v2 model on test set...

=======================================================
📊 PHASE 1 vs PHASE 2A COMPARISON
=======================================================

Metric                    Phase 1   Phase 2A     Change
------------------------------------------------------
Accuracy                   61.88%     60.38%     -1.50%
F1 weighted                0.5971     0.6054    +0.0083
FAKE recall                 36.5%      61.3%
REAL recall                 81.5%      59.7%

🔢 Confusion Matrix (v2):
                 Predicted
                 FAKE    REAL
  Actual FAKE  [  339    214 ]
  Actual REAL  [  288    426 ]

              precision    recall  f1-score   support

    FAKE (0)     0.5407    0.6130    0.5746       553
    REAL (1)     0.6656    0.5966    0.6292       714

    accuracy                         0.6038      1267
   macro avg     0.6031    0.6048    0.6019      1267
weighted avg     0.6111    0.6038    0.6054      1267

In [22]:
# ============================================================
# Save the improved v2 model to Google Drive
# ============================================================

import json, os
from datetime import datetime

SAVE_PATH_V2 = "/content/drive/MyDrive/MisinformationGuard/model_v2"
os.makedirs(SAVE_PATH_V2, exist_ok=True)

print("⏳ Saving Phase 2A model...")
model_v2.save_pretrained(SAVE_PATH_V2)
tokenizer.save_pretrained(SAVE_PATH_V2)

# Save updated metrics
metrics_v2 = {
    "project"         : "Misinformation Guard",
    "phase"           : "Phase 2A — Class Weighted Retraining",
    "model"           : "xlm-roberta-base + weighted loss",
    "date_trained"    : datetime.now().strftime("%Y-%m-%d %H:%M"),
    "improvement_over": "Phase 1",
    "test_accuracy"   : 0.6038,
    "f1_weighted"     : 0.6054,
    "f1_macro"        : 0.6019,
    "fake_recall"     : 0.6130,
    "real_recall"     : 0.5966,
    "fake_caught"     : 339,
    "fake_missed"     : 214,
    "key_win"         : "FAKE recall improved from 36.5% to 61.3% (+24.8%)",
    "confusion_matrix": {
        "TN": 339, "FP": 214,
        "FN": 288, "TP": 426
    }
}

with open(f"{SAVE_PATH_V2}/training_metrics.json", "w") as f:
    json.dump(metrics_v2, f, indent=2)

print("✅ Model v2 saved to Google Drive!")
print(f"   Path: {SAVE_PATH_V2}")
print("\n📁 Files saved:")
for f in sorted(os.listdir(SAVE_PATH_V2)):
    size = os.path.getsize(f"{SAVE_PATH_V2}/{f}") / 1e6
    print(f"   {f:45s} {size:6.1f} MB")

⏳ Saving Phase 2A model...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

✅ Model v2 saved to Google Drive!
   Path: /content/drive/MyDrive/MisinformationGuard/model_v2

📁 Files saved:
   config.json                                      0.0 MB
   model.safetensors                             1112.2 MB
   tokenizer.json                                  17.1 MB
   tokenizer_config.json                            0.0 MB
   training_metrics.json                            0.0 MB